version: '3.8'
services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: building
      MYSQL_DATABASE: building
      MYSQL_USER: building
      MYSQL_PASSWORD: building123
    ports:
      - "3310:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: